level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Getting Started",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Introduction",null,false,false,null,null,"","introduction.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"AWS Overview",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Development Process",null,false,false,null,null,"","development_process.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Earning Money with AWS",null,false,false,null,null,"","earning_money.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Writing Applications Using Web Services",null,false,false,null,null,"","writing_applications.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using the Developer’s Message Board",null,false,false,null,null,"","message_boards.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Data Flow",null,false,false,null,null,"","data_flow.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Data Model",null,false,false,null,null,"","data_model.htm","right",false);
addItem(level2,level1);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Search, Sort, and Parameter Types",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Parameter Types",null,false,false,null,null,"","parameter_types.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Sort Types",null,false,false,null,null,"","sort_types.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Search Types",null,false,false,null,null,"","search_types.htm","right",true);
addItem(level2,level1);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Accessing Amazon Web Services",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using SOAP",null,false,false,null,null,"","using_soap.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using XML",null,false,false,null,null,"","using_xml.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using XSLT",null,false,false,null,null,"",null,"right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using XSLT",null,false,false,null,null,"","using_xslt.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using XSLT Stylesheets",null,false,false,null,null,"","using_xslt_stylesheets.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Request Parameter Access",null,false,false,null,null,"","using_xslt_request_parameter_access.htm","right",true);
addItem(level2,level1);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Search This Kit",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Search",null,false,false,null,null,"","DevaSearch/search.html","right",true);
addItem(level1,level0);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"New in this Release",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using XML3 in AWS Calls",null,false,false,null,null,"","new_feature_xml3.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Working with Apparel Data",null,false,false,null,null,"","mode_apparal.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"XSLT Request Parameter Access",null,false,false,null,null,"","using_xslt_request_parameter_access.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Price Range Searches",null,false,false,null,null,"","price_range_searches.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Keyword Searches in a Browse Node",null,false,false,null,null,"","search_browse_keywords.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Additional Power Search Features",null,false,false,null,null,"","search_power.htm","right",true);
addItem(level1,level0);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Product and Catalog Data",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Product Data Overview",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using Catalog Data",null,false,false,null,null,"","using_catalog_data.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Product Relationships",null,false,false,null,null,"","product_variation_relationships.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Generating Additional Product Results",null,false,false,null,null,"","generating_additional_results.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using Offerings",null,false,false,null,null,"","using_offerings.htm","right",true);
addItem(level2,level1);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Actor/Actress Searches",null,false,false,null,null,"","search_actor.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Artist/Musician Searches",null,false,false,null,null,"","search_artist.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"ASIN and ISBN Searches",null,false,false,null,null,"","search_asin_isbn.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Author Searches",null,false,false,null,null,"","search_author.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Blended Results Searches",null,false,false,null,null,"","search_blended.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Browse Node Searches",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Browse Node Searches",null,false,false,null,null,"","search_browse.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Keyword Searches in a Browse Node",null,false,false,null,null,"","search_browse_keywords.htm","right",true);
addItem(level2,level1);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Director Searches",null,false,false,null,null,"","search_director.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Exchange Searches ",null,false,false,null,null,"","search_exchanges.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Keyword Searches",null,false,false,null,null,"","search_keywords.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Listmania! Searches",null,false,false,null,null,"","search_listmania.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Manufacturer Searches",null,false,false,null,null,"","search_manufacturer.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Manufacturer Searches",null,false,false,null,null,"","search_manufacturer.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Power Searches",null,false,false,null,null,"","search_power.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Seller Profile Searches",null,false,false,null,null,"","search_seller_profiles.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Similarities Searches",null,false,false,null,null,"","search_similarities.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Third Party Searches",null,false,false,null,null,"","search_third_party.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"UPC Searches",null,false,false,null,null,"","search_upc.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Wishlist Searches",null,false,false,null,null,"","search_wishlist.htm","right",true);
addItem(level1,level0);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Enabling Purchases",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Adding Items to Shopping Carts",null,false,false,null,null,"","add_to_cart.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Enabling Transactions",null,false,false,null,null,"","enabling_transactions.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using Quick Click",null,false,false,null,null,"","using_quick_click.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Using the Remote Shopping Cart",null,false,false,null,null,"",null,"right",false);
addItem(level1,level0);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using the Remote Shopping Cart",null,false,false,null,null,"","remote_shopping_cart.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Remote Shopping Cart via XML",null,false,false,null,null,"","remote_soap_cart.htm","right",false);
addItem(level2,level1);
level2 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Remote Shopping Cart via SOAP",null,false,false,null,null,"","remote_soap_cart.htm","right",true);
addItem(level2,level1);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Selling on Amazon.com",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"placeholder",null,false,false,null,null,"","add_to_cart.htm","right",true);
addItem(level1,level0);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"International Data",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Using International Data",null,false,false,null,null,"","using_international_data.htm","right",true);
addItem(level1,level0);
level0 = new Item("folderstyle/folderc.gif","folderstyle/foldero.gif",null,null,16,16,"Reference",null,false,false,null,null,"",null,"right",false);
addItem(level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"About this SDK",null,false,false,null,null,"","document_information.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Amazon Terminology",null,false,false,null,null,"","amazon_terminology.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Common Product Modes and Browse IDs",null,false,false,null,null,"","common_modes.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Constraints and Limitations",null,false,false,null,null,"","constraints_and_limitations.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"DTD, XSD and SOAP WSDL",null,false,false,null,null,"","dtd_xsd_soap_wsdl.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Publishing Your Application",null,false,false,null,null,"","publishing_your_application.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"References and Resources",null,false,false,null,null,"","references.htm","right",false);
addItem(level1,level0);
level1 = new Item("folderstyle/leaf.gif",null,null,null,16,16,"Web Services Glossary",null,false,false,null,null,"","glossary.htm","right",true);
addItem(level1,level0);
renderSitemap("TREE", false, null, null, null, "surfmapjs/");